metrics:
  # Model Performance Metrics
  model_accuracy:
    type: gauge
    description: "Model prediction accuracy"
    labels:
      - model_id
      - version
      - dataset

  model_latency:
    type: histogram
    description: "Model prediction latency in seconds"
    buckets: [0.01, 0.05, 0.1, 0.5, 1.0, 5.0]
    labels:
      - model_id
      - version
      - endpoint

  prediction_throughput:
    type: counter
    description: "Number of predictions processed"
    labels:
      - model_id
      - version
      - status

  # Training Metrics
  training_duration:
    type: gauge
    description: "Model training duration in seconds"
    labels:
      - model_id
      - version

  training_loss:
    type: gauge
    description: "Model training loss"
    labels:
      - model_id
      - version
      - phase

  # Resource Usage Metrics
  gpu_memory_usage:
    type: gauge
    description: "GPU memory usage in bytes"
    labels:
      - device
      - model_id

  batch_processing_time:
    type: histogram
    description: "Batch processing time in seconds"
    buckets: [0.1, 0.5, 1.0, 2.0, 5.0]
    labels:
      - model_id
      - batch_size

  # Data Quality Metrics
  data_drift_score:
    type: gauge
    description: "Data drift detection score"
    labels:
      - model_id
      - feature

  validation_score:
    type: gauge
    description: "Data validation score"
    labels:
      - model_id
      - validation_type

alerts:
  # Performance Alerts
  high_latency:
    condition: "thunderai_model_latency_seconds > 1.0"
    duration: "5m"
    severity: warning
    annotations:
      summary: "High model latency detected"
      description: "Model {{ $labels.model_id }} latency is above 1 second"

  accuracy_drop:
    condition: "thunderai_model_accuracy < 0.9"
    duration: "15m"
    severity: critical
    annotations:
      summary: "Model accuracy degradation"
      description: "Model {{ $labels.model_id }} accuracy dropped below 90%"

  # Resource Alerts
  high_memory_usage:
    condition: "thunderai_gpu_memory_usage > 0.9"
    duration: "5m"
    severity: warning
    annotations:
      summary: "High GPU memory usage"
      description: "GPU memory usage is above 90%"

  # Data Quality Alerts
  data_drift_detected:
    condition: "thunderai_data_drift_score > 0.7"
    duration: "10m"
    severity: warning
    annotations:
      summary: "Data drift detected"
      description: "High data drift detected for model {{ $labels.model_id }}"

recording_rules:
  model_slo_compliance:
    expr: |
      sum(rate(thunderai_model_latency_seconds_bucket{le="0.1"}[5m]))
      /
      sum(rate(thunderai_model_latency_seconds_count[5m]))
    labels:
      slo: "latency"
    record: thunderai:slo:compliance

  prediction_success_rate:
    expr: |
      sum(rate(thunderai_prediction_throughput{status="success"}[5m]))
      /
      sum(rate(thunderai_prediction_throughput[5m]))
    record: thunderai:prediction:success_rate 