apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: thunderai-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thunderai-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 