apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-retraining
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: model-retraining
        spec:
          containers:
          - name: retraining
            image: thunderai-retraining:latest
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
                nvidia.com/gpu: 1
              limits:
                memory: "8Gi"
                cpu: "4"
                nvidia.com/gpu: 1
            env:
            - name: MODEL_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: thunderai-config
                  key: model_registry_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: thunderai-secrets
                  key: database_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: thunderai-secrets
                  key: redis_url
            volumeMounts:
            - name: model-storage
              mountPath: /models
            - name: training-data
              mountPath: /data
            - name: config
              mountPath: /config
          volumes:
          - name: model-storage
            persistentVolumeClaim:
              claimName: model-storage-pvc
          - name: training-data
            persistentVolumeClaim:
              claimName: training-data-pvc
          - name: config
            configMap:
              name: retraining-config
          restartPolicy: OnFailure
          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: retraining-config
data:
  config.yaml: |
    retraining:
      batch_size: 32
      learning_rate: 0.0001
      epochs: 10
      validation_split: 0.2
      early_stopping:
        patience: 3
        min_delta: 0.001
      performance_threshold: 0.9
      data_drift_threshold: 0.1
      monitoring:
        enabled: true
        metrics_interval: 60
        alert_threshold: 0.8 