apiVersion: v1
kind: ConfigMap
metadata:
  name: thunderai-staging-config
  namespace: staging
data:
  ENVIRONMENT: "staging"
  LOG_LEVEL: "DEBUG"
  MODEL_STORAGE_PATH: "/app/models"
  ENABLE_DEBUG: "true"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
  CACHE_TTL: "1800"  # 30 minutes
  MAX_BATCH_SIZE: "16"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunderai-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thunderai
      env: staging
  template:
    metadata:
      labels:
        app: thunderai
        env: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: thunderai
        image: thunderai:staging
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: thunderai-staging-config
              key: ENVIRONMENT
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: config
          mountPath: /app/config
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc-staging
      - name: config
        configMap:
          name: thunderai-staging-config

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thunderai-staging-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thunderai-staging
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 