apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-manager
  template:
    metadata:
      labels:
        app: workflow-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: workflow-manager
        image: thunderai-workflow:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: redis-url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: database-url
        - name: PREFECT_API_URL
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: prefect-api-url
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: workflow-storage
          mountPath: /workflows
        - name: workflow-config
          mountPath: /config
      volumes:
      - name: workflow-storage
        persistentVolumeClaim:
          claimName: workflow-storage-pvc
      - name: workflow-config
        configMap:
          name: workflow-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
data:
  config.yaml: |
    workflow_manager:
      max_concurrent_workflows: 10
      workflow_timeout: 3600
      retry_policy:
        max_retries: 3
        retry_interval: 60
      monitoring:
        metrics_interval: 30
        alert_thresholds:
          error_rate: 0.1
          latency: 300
      storage:
        retention_days: 30
        backup_enabled: true

---
apiVersion: v1
kind: Service
metadata:
  name: workflow-manager
spec:
  selector:
    app: workflow-manager
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 